### PR TITLE
fix: do not override getters in scoped store

### LINKED ISSUE #77: Computed State does not work as expected with arrays
This is probably something I'm doing incorrectly, but I've ran into this issue when attempting to create some basic derived state
when attempting to create some basic derived state from an array within my store;

This is a scoped store with initial values set via SSR. I can access the values set with no issues, but as soon as I try to access derived state, nothing is actually returning.

my store

```
'use client'

import { createScopedStore } from "stan-js"

export const { StoreProvider, useScopedStore, useStore } = createScopedStore({
    testArray: [], 
    testArray2: [1,2,3,4,5,6,7,8,9,10],
    get testArrayComputed () {
        return this.testArray.filter((item) => item % 2 === 0);
    },
    get testArray2Computed () {
        return this.testArray2.filter((item) => item % 2 === 0);
    }
});
```

In this scenario testArray is set to [1,2,3,4,5,6,7,8,9,10] as an initialValue. Unfortunately testArrayComputed will only return an empty array no matter what I do.  testArray2Computed works as expected.

### PR DESCRIPTION
**Pull request by ceski23**
Fixes #77

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -39,3 +39,18 @@ export const equal = <T>(a: T, b: T) => {
 
     return keysA.every(key => Object.is(a[key], b[key]) && Object.prototype.hasOwnProperty.call(b, key))
 }
+
+export const mergeState = <TState extends object>(state: TState, partialState: Partial<RemoveReadonly<TState>>) => {
+    const newState = { ...state }
+
+    Object.defineProperties(newState, Object.getOwnPropertyDescriptors(state))
+    Object.keys(partialState ?? {}).forEach(key => {
```
Comment (Brentlok) [inline src/utils.ts:47]: unnecessary empty obj

**Review by Brentlok — APPROVED** [review]
