### PR TITLE
fix: scoped store with react compiler

### LINKED ISSUE #75: Hooks must be the same function on every render
When using stan paired with the react-compiler ESLint rules as per documentation, the scoped store seems to violate one of the [rules of hooks](https://react.dev/reference/rules/react-calls-components-and-hooks#dont-dynamically-use-hooks), not sure if this is just an edge case

image
image

```tsx
import { createScopedStore } from "stan-js";
import { storage } from "stan-js/storage";

const { StoreProvider, useScopedStore, withStore } = createScopedStore({
    isBottomBarExpanded: storage(false),
});
```

### PR DESCRIPTION
**Pull request by Brentlok**
fixes #75

### CODE REVIEW

File: examples/nextjs/src/store.ts [hunk 1]
```diff
@@ -1,8 +1,8 @@
 'use client'
 
-import { createScopedStore } from 'stan-js'
+import { createScopedStore } from '../../../dist'
```
Comment (ceski23) [inline examples/nextjs/src/store.ts:3]: won't work in stackblitz

**Review by ceski23 — CHANGES_REQUESTED** [review]

File: examples/nextjs/src/store.ts (hunk 1 above)
Comment (Brentlok) [reply examples/nextjs/src/store.ts:3]: forgot to revert that 🙈

**Review by ceski23 — APPROVED** [review]
LGTM!
